### ISSUE TITLE
Request values not available after Verify

### ISSUE THREAD

**Issue by gravis** [haisum/recaptcha#6]
Hi,

I have hit a (very) strange bug with this lib.
Considering the following code:

``` go
m.HandleFunc("/contact", func(w http.ResponseWriter, r *http.Request) {
    // recaptcha check
    re := recaptcha.R{
        Secret: "secret",
    }
    if re.Verify(*r) {
        log.Info("Valid captcha")
    } else {
        fmt.Fprintf(w, "Invalid! These errors ocurred: %v", re.LastError())
        log.Info("Valid captcha")
        return
    }

    m := gomail.NewMessage()
    m.SetHeader("From", r.FormValue("email"))
    [...]
}
```

This is actually failing, because `r.FormValue("email")` is empty.
If I update your lib to use a ref instead of a request copy, hence:

``` go
    if re.Verify(r) { // Pass request by ref instead of value
        log.Info("Valid captcha")
    } else {
        fmt.Fprintf(w, "Invalid! These errors ocurred: %v", re.LastError())
        log.Info("Valid captcha")
        return
    }
```

It's working. I can't explain yet that behaviour, but could you consider using a ref instead of a request by value?

Thanks

**Comment by gravis** [comment]
for the record: http://stackoverflow.com/questions/38983089/http-request-values-are-empty-if-the-request-is-passed-by-value

**Comment by haisum** [comment]
You got the answer on Stackoverflow. I am closing this for now. If you have any suggestion on improving code, re-open the issue with comments.
